#change this to your own repo, should you have uploaded your image!
FROM  node:8-alpine
MAINTAINER Nattapht Laoharawee <nattaphat@witsawa.com>
RUN mkdir /app
WORKDIR /app
COPY package.json /app/
RUN npm install
COPY server.js /app/
COPY www /app/www/
EXPOSE 8080

CMD node .